### PR TITLE
Fix chapter page detection storage

### LINKED ISSUE #60: [UI] Tracking bugs and makes trash bin disappear while browsing
**Describe the bug**
While browsing a registered comic, the tracking is not visible, and even the trash bin icon disappears.
Looking at the console output, it seems that some internal messaging stuff is erroneous and fails to provide the expected functionality.

**Expected behavior**
Tracking should be updated, and the '>' button should blink green (or red) to notify the user of the update status.

**To Reproduce**
1. Go to any manga on mangaeden.com
2. Add it to the tracking
3. Browse the manga for a while
4. At some point, the trash bin icon should disappear, and the following should be logged into the console:
```
BmcSidePanel: received message to display status notification op=track err=Unknown  strings.js:264:5
Unknown string load-bookmarks.js:390:17
    addEvents moz-extension://e7fde39b-ded5-4d24-8b84-25a07f524e08/scripts/load-bookmarks.js:390
    setupMessaging moz-extension://e7fde39b-ded5-4d24-8b84-25a07f524e08/engine/messaging.js:133
    setupMessaging moz-extension://e7fde39b-ded5-4d24-8b84-25a07f524e08/engine/messaging.js:131
```

**Desktop:**
 - Browser: Firefox

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #60.

To be merged after #61.

### CODE REVIEW

File: web-extensions/chrome/engine/datamodel.js [hunk 1]
```diff
@@ -435,17 +435,27 @@ BmcDataAPI.prototype.updateComic = function(comicId, chapter, page, cb) {
...
-                && (payload.tracking.page && page
-                    && payload.tracking.page > page))) {
-            return cb(new Error(LOCALIZATION.getString('S22')));
+        if (payload.tracking.chapter !== undefined && payload.tracking.page !== undefined) {
+            const trackChapter = parseInt(payload.tracking.chapter);
+            const trackPage = parseInt(payload.tracking.page);
+            const currentChapter = parseInt(chapter);
+            const currentPage = parseInt(page);
+
+            if (trackChapter > currentChapter || trackPage > currentPage) {
```
Comment (Joacchim) [inline web-extensions/chrome/engine/datamodel.js]: nope,  trackPage might be higher than currentPage, while currentChapter is higher than trackChapter.
We need to check that either:
1. trackChapter is strictly greater than currentChapter
2. trackChapter is equal to currentChapter AND trackPage is greater than currentPage

Here, we're failing the second check, and possibly creating another bug :)

File: web-extensions/chrome/engine/datamodel.js [hunk 2]
```diff
@@ -435,17 +435,27 @@ BmcDataAPI.prototype.updateComic = function(comicId, chapter, page, cb) {
          * once. We may actually want to accept that, though.
          * Similarly, we may want to allow backwards-tracking too.. ?
          */
-        if (payload.tracking.chapter > chapter
-            || (payload.tracking.chapter == chapter
-                && (payload.tracking.page && page
-                    && payload.tracking.page > page))) {
-            return cb(new Error(LOCALIZATION.getString('S22')));
+        if (payload.tracking.chapter !== undefined && payload.tracking.page !== undefined) {
```
Comment (Joacchim) [inline web-extensions/chrome/engine/datamodel.js]: Since the code was originally written, it's become possible to have an undefined `page` (cases where a chapter can be read as a whole and not page-by-page).
We should account for it.

File: web-extensions/chrome/engine/datamodel.js [hunk 3]
```diff
@@ -435,17 +435,27 @@ BmcDataAPI.prototype.updateComic = function(comicId, chapter, page, cb) {
...
+            const trackChapter = parseInt(payload.tracking.chapter);
+            const trackPage = parseInt(payload.tracking.page);
+            const currentChapter = parseInt(chapter);
+            const currentPage = parseInt(page);
+
+            if (trackChapter > currentChapter || trackPage > currentPage) {
+                LOGS.warn('S22');
+                // Re-tracking the last tracked page; Reload ? OR clicked on last read ?
```
Comment (Joacchim) [inline web-extensions/chrome/engine/datamodel.js]: I don't get why this line of comment was pasted here: This is not the case (we check '>', and not `==`
Here, we've attempted to update the tracking with an "older"/"previous" page. (hence the warn just before).

That being said, the next line is still valid.

File: web-extensions/chrome/engine/datamodel.js [hunk 4]
```diff
@@ -435,17 +435,27 @@ BmcDataAPI.prototype.updateComic = function(comicId, chapter, page, cb) {
...
+                // anyways -> Early return, while ensuring we're not growing the stack
+                return setTimeout(() => cb(null), 0);
+            }
         }
         // Re-tracking the last tracked page; Reload ? OR clicked on last read ?
         // anyways -> Early return, while ensuring we're not growing the stack
         if (payload.tracking.chapter === chapter && payload.tracking.page === page) {
             return setTimeout(() => cb(null), 0);
         }
+        if (typeof chapter === 'undefined' || typeof page === 'undefined') {
```
Comment (Joacchim) [inline web-extensions/chrome/engine/datamodel.js]: Same here, page should accept an undefined value (for chapter-only based readers)

File: web-extensions/chrome/engine/datamodel.js (hunk 1 above)
Comment (GuillaumeGomez) [reply web-extensions/chrome/engine/datamodel.js]: Good catch!

**Comment by GuillaumeGomez** [comment]
Updated.
